### ISSUE TITLE
Runtime error.

### ISSUE THREAD

**Issue by BBaysinger** [nsmolenskii/ng-demo-app#2]
When I run this I get:

```
Unhandled Promise rejection: Template parse errors:
'md-input' is not a known element:
1. If 'md-input' is an Angular component, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
  </md-card-title>
  <md-card-content>
    [ERROR ->]<md-input [(ngModel)]="name" placeholder="Give the name"></md-input>
  </md-card-content>
</md-card>
"): GreeterComponent@5:4 ; Zone: <root> ; Task: Promise.then ; Value: SyntaxError Error: Template parse errors:
'md-input' is not a known element:
1. If 'md-input' is an Angular component, then verify that it is part of this module.
2. If 'md-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
  </md-card-title>
  <md-card-content>
    [ERROR ->]<md-input [(ngModel)]="name" placeholder="Give the name"></md-input>
  </md-card-content>
</md-card>
"): GreeterComponent@5:4
    at SyntaxError.ZoneAwareError (http://localhost:4200/vendor.bundle.js:108200:33)
    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:77654:16)
    at new SyntaxError (http://localhost:4200/vendor.bundle.js:6264:16)
    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:19704:19)
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:54011:68)
    at http://localhost:4200/vendor.bundle.js:53894:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:53894:19)
    at createResult (http://localhost:4200/vendor.bundle.js:53776:19)
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:107542:26)
    at Zone.run (http://localhost:4200/vendor.bundle.js:107334:43)
    at http://localhost:4200/vendor.bundle.js:107921:57
    at ZoneDelegate.invokeTask (http://localhost:4200/vendor.bundle.js:107575:31)
    at Zone.runTask (http://localhost:4200/vendor.bundle.js:107374:47)
    at drainMicroTaskQueue (http://localhost:4200/vendor.bundle.js:107754:35)
```

**Comment by nsmolenskii** [comment]
Seems to be an issue related to backward compatibility of @angular/material2. I will update dependency to actual versions

**Comment by nsmolenskii** [comment]
Used libraries updated to actual versions. Should work now.
